# Generated by Django 4.2 on 2026-06-17 20:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('identificacion', models.CharField(db_index=True, max_length=20, unique=True)),
                ('razon_social', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('celular', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LineaServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('linea_numero', models.PositiveSmallIntegerField()),
                ('estado', models.CharField(choices=[('NO_INSTALADO', 'NO_INSTALADO'), ('ACTIVO', 'ACTIVO'), ('SUSPENDIDO', 'SUSPENDIDO'), ('CANCELADO', 'CANCELADO')], default='NO_INSTALADO', max_length=20)),
                ('fecha_instalacion', models.DateField(blank=True, null=True)),
                ('saldo_vencido', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='core.cliente')),
            ],
            options={
                'unique_together': {('cliente', 'linea_numero')},
            },
        ),
        migrations.CreateModel(
            name='Rubro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('NO_PAGADO', 'NO_PAGADO'), ('PAGADO', 'PAGADO'), ('VENCIDO', 'VENCIDO'), ('ANULADO', 'ANULADO')], default='NO_PAGADO', max_length=20)),
                ('fecha_emision', models.DateTimeField()),
                ('fecha_vencimiento', models.DateTimeField()),
                ('fecha_pago', models.DateTimeField(blank=True, null=True)),
                ('linea_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubros', to='core.lineaservicio')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ColeccionRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SUCCESS', 'SUCCESS'), ('FAILED', 'FAILED')], max_length=20)),
                ('unpaid_count', models.PositiveSmallIntegerField()),
                ('action_taken', models.CharField(choices=[('NONE', 'NONE'), ('SUSPEND', 'SUSPEND'), ('UNSUSPEND', 'UNSUSPEND')], default='NONE', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('linea_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core.lineaservicio')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
